"""Update relationships

Revision ID: 456bc21ad31a
Revises: 4885af0bf624
Create Date: 2024-11-25 15:42:29.300046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456bc21ad31a'
down_revision = '4885af0bf624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
