"""Add participant_id to answers

Revision ID: 4885af0bf624
Revises: e7b2a7f454fb
Create Date: 2024-11-25 15:41:12.093443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4885af0bf624'
down_revision = 'e7b2a7f454fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_id', sa.String(length=36), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('participant_id')

    # ### end Alembic commands ###
